<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="Anushas-MacBook-Pro.local" failures="10" tests="145" name="test_runner_team08.TestRunner" time="28.820" errors="3" timestamp="2024-04-02T13:15:39 EDT" skipped="0">
  <testcase classname="test_runner_team08.TestRunner" name="runScenario" time="0.145"/>
  <testcase classname="test_runner_team08.TestRunner" name="runScenario" time="0.126"/>
  <testcase classname="test_runner_team08.TestRunner" name="runScenario" time="0.148"/>
  <testcase classname="test_runner_team08.TestRunner" name="runScenario" time="0.131"/>
  <testcase classname="test_runner_team08.TestRunner" name="runScenario" time="0.135">
    <failure message="batchName expected:&lt;200&gt; but was:&lt;404&gt;" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: batchName expected:<200> but was:<404>
at org.junit.Assert.fail(Assert.java:93)
at org.junit.Assert.failNotEquals(Assert.java:647)
at org.junit.Assert.assertEquals(Assert.java:128)
at org.junit.Assert.assertEquals(Assert.java:472)
at utilities_team08.CommonValidation.statusValidations(CommonValidation.java:71)
at step_definition_team08.BatchStepDefinition.admin_receives_ok_status_with_message(BatchStepDefinition.java:389)
at ✽.Admin receives 200 Ok status with message batch(file:///Users/anushakarthick/NumpyNinja/Team_08_APIArchitects_RestAssured/src/test/resources/features/003_BatchModule.feature:227)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase classname="test_runner_team08.TestRunner" name="runScenario" time="0.151"/>
  <testcase classname="test_runner_team08.TestRunner" name="runScenario" time="0.144"/>
  <testcase classname="test_runner_team08.TestRunner" name="runScenario" time="0.124"/>
  <testcase classname="test_runner_team08.TestRunner" name="runScenario" time="0.135"/>
  <testcase classname="test_runner_team08.TestRunner" name="runScenario" time="0.134"/>
  <testcase classname="test_runner_team08.TestRunner" name="runScenario" time="0.131"/>
  <testcase classname="test_runner_team08.TestRunner" name="runScenario" time="0.124"/>
  <testcase classname="test_runner_team08.TestRunner" name="runScenario" time="0.129"/>
  <testcase classname="test_runner_team08.TestRunner" name="runScenario" time="0.176"/>
  <testcase classname="test_runner_team08.TestRunner" name="runScenario" time="0.130"/>
  <testcase classname="test_runner_team08.TestRunner" name="runScenario" time="0.230"/>
  <testcase classname="test_runner_team08.TestRunner" name="runScenario" time="0.511">
    <failure message="Status validation expected:&lt;400&gt; but was:&lt;201&gt;" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Status validation expected:<400> but was:<201>
at org.junit.Assert.fail(Assert.java:93)
at org.junit.Assert.failNotEquals(Assert.java:647)
at org.junit.Assert.assertEquals(Assert.java:128)
at org.junit.Assert.assertEquals(Assert.java:472)
at utilities_team08.CommonValidation.statusValidations(CommonValidation.java:71)
at step_definition_team08.UserModuleStepDefinition.admin_receives_bad_request_status_with_message_and_boolean_success_details(UserModuleStepDefinition.java:286)
at ✽.Admin receives 400 Bad Request Status with message and boolean success details(file:///Users/anushakarthick/NumpyNinja/Team_08_APIArchitects_RestAssured/src/test/resources/features/004_User_Module_and_BatchProgramMap.feature:50)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase classname="test_runner_team08.TestRunner" name="runScenario" time="0.201"/>
  <testcase classname="test_runner_team08.TestRunner" name="runScenario" time="0.129"/>
  <testcase classname="test_runner_team08.TestRunner" name="runScenario" time="0.139"/>
  <testcase classname="test_runner_team08.TestRunner" name="runScenario" time="0.124"/>
  <testcase classname="test_runner_team08.TestRunner" name="runScenario" time="0.136"/>
  <testcase classname="test_runner_team08.TestRunner" name="runScenario" time="0.120"/>
  <testcase classname="test_runner_team08.TestRunner" name="runScenario" time="0.127"/>
  <testcase classname="test_runner_team08.TestRunner" name="runScenario" time="0.173"/>
  <testcase classname="test_runner_team08.TestRunner" name="runScenario" time="0.125">
    <failure message="1 expectation failed.
Expected status code &lt;404&gt; but was &lt;400&gt;.
" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: 1 expectation failed.
Expected status code <404> but was <400>.

at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62)
at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502)
at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:486)
at org.codehaus.groovy.reflection.CachedConstructor.invoke(CachedConstructor.java:73)
at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrapNoCoerce.callConstructor(ConstructorSite.java:108)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:277)
at io.restassured.internal.ResponseSpecificationImpl$HamcrestAssertionClosure.validate(ResponseSpecificationImpl.groovy:512)
at io.restassured.internal.ResponseSpecificationImpl$HamcrestAssertionClosure$validate$1.call(Unknown Source)
at io.restassured.internal.ResponseSpecificationImpl.validateResponseIfRequired(ResponseSpecificationImpl.groovy:696)
at io.restassured.internal.ResponseSpecificationImpl.this$2$validateResponseIfRequired(ResponseSpecificationImpl.groovy)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.codehaus.groovy.runtime.callsite.PlainObjectMetaMethodSite.doInvoke(PlainObjectMetaMethodSite.java:43)
at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:198)
at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.callCurrent(PogoMetaMethodSite.java:62)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:185)
at io.restassured.internal.ResponseSpecificationImpl.statusCode(ResponseSpecificationImpl.groovy:135)
at io.restassured.specification.ResponseSpecification$statusCode$0.callCurrent(Unknown Source)
at io.restassured.internal.ResponseSpecificationImpl.statusCode(ResponseSpecificationImpl.groovy:143)
at io.restassured.internal.ValidatableResponseOptionsImpl.statusCode(ValidatableResponseOptionsImpl.java:89)
at step_definition_team08.BatchStepDefinition.admin_receives_not_found_status_with_message_and_boolean_success_details_batch_1(BatchStepDefinition.java:590)
at ✽.Admin receives 404 Not Found Status with the message and boolean success details batch(file:///Users/anushakarthick/NumpyNinja/Team_08_APIArchitects_RestAssured/src/test/resources/features/003_BatchModule.feature:146)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase classname="test_runner_team08.TestRunner" name="runScenario" time="0.122">
    <failure message="Status expected:&lt;200&gt; but was:&lt;404&gt;" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Status expected:<200> but was:<404>
at org.junit.Assert.fail(Assert.java:93)
at org.junit.Assert.failNotEquals(Assert.java:647)
at org.junit.Assert.assertEquals(Assert.java:128)
at org.junit.Assert.assertEquals(Assert.java:472)
at utilities_team08.CommonValidation.statusValidations(CommonValidation.java:71)
at step_definition_team08.UserProgramBatchMapStepDefinition.admin_receives_ok(UserProgramBatchMapStepDefinition.java:48)
at ✽.Admin  receives 200 OK(file:///Users/anushakarthick/NumpyNinja/Team_08_APIArchitects_RestAssured/src/test/resources/features/004_User_Module_and_BatchProgramMap.feature:323)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase classname="test_runner_team08.TestRunner" name="runScenario" time="0.131"/>
  <testcase classname="test_runner_team08.TestRunner" name="runScenario" time="0.122"/>
  <testcase classname="test_runner_team08.TestRunner" name="runScenario" time="0.119"/>
  <testcase classname="test_runner_team08.TestRunner" name="runScenario" time="0.137"/>
  <testcase classname="test_runner_team08.TestRunner" name="runScenario" time="0.135"/>
  <testcase classname="test_runner_team08.TestRunner" name="runScenario" time="0.115"/>
  <testcase classname="test_runner_team08.TestRunner" name="runScenario" time="0.134"/>
  <testcase classname="test_runner_team08.TestRunner" name="runScenario" time="0.120"/>
  <testcase classname="test_runner_team08.TestRunner" name="runScenario" time="0.119"/>
  <testcase classname="test_runner_team08.TestRunner" name="runScenario" time="0.144"/>
  <testcase classname="test_runner_team08.TestRunner" name="runScenario" time="0.155"/>
  <testcase classname="test_runner_team08.TestRunner" name="runScenario" time="0.259"/>
  <testcase classname="test_runner_team08.TestRunner" name="runScenario" time="0.681"/>
  <testcase classname="test_runner_team08.TestRunner" name="runScenario" time="0.243"/>
  <testcase classname="test_runner_team08.TestRunner" name="runScenario" time="0.122"/>
  <testcase classname="test_runner_team08.TestRunner" name="runScenario" time="0.488">
    <failure message="Status validation expected:&lt;400&gt; but was:&lt;201&gt;" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Status validation expected:<400> but was:<201>
at org.junit.Assert.fail(Assert.java:93)
at org.junit.Assert.failNotEquals(Assert.java:647)
at org.junit.Assert.assertEquals(Assert.java:128)
at org.junit.Assert.assertEquals(Assert.java:472)
at utilities_team08.CommonValidation.statusValidations(CommonValidation.java:71)
at step_definition_team08.UserModuleStepDefinition.admin_receives_bad_request_status_with_message_and_boolean_success_details(UserModuleStepDefinition.java:286)
at ✽.Admin receives 400 Bad Request Status with message and boolean success details(file:///Users/anushakarthick/NumpyNinja/Team_08_APIArchitects_RestAssured/src/test/resources/features/004_User_Module_and_BatchProgramMap.feature:50)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase classname="test_runner_team08.TestRunner" name="runScenario" time="0.154"/>
  <testcase classname="test_runner_team08.TestRunner" name="runScenario" time="0.134"/>
  <testcase classname="test_runner_team08.TestRunner" name="runScenario" time="0.165"/>
  <testcase classname="test_runner_team08.TestRunner" name="runScenario" time="0.122"/>
  <testcase classname="test_runner_team08.TestRunner" name="runScenario" time="0.173"/>
  <testcase classname="test_runner_team08.TestRunner" name="runScenario" time="0.357"/>
  <testcase classname="test_runner_team08.TestRunner" name="runScenario" time="0.119"/>
  <testcase classname="test_runner_team08.TestRunner" name="runScenario" time="1.719"/>
  <testcase classname="test_runner_team08.TestRunner" name="runScenario" time="0.136"/>
  <testcase classname="test_runner_team08.TestRunner" name="runScenario" time="0.128"/>
  <testcase classname="test_runner_team08.TestRunner" name="runScenario" time="0.144"/>
  <testcase classname="test_runner_team08.TestRunner" name="runScenario" time="0.126"/>
  <testcase classname="test_runner_team08.TestRunner" name="runScenario" time="0.275"/>
  <testcase classname="test_runner_team08.TestRunner" name="runScenario" time="0.141"/>
  <testcase classname="test_runner_team08.TestRunner" name="runScenario" time="0.144"/>
  <testcase classname="test_runner_team08.TestRunner" name="runScenario" time="0.138"/>
  <testcase classname="test_runner_team08.TestRunner" name="runScenario" time="0.125"/>
  <testcase classname="test_runner_team08.TestRunner" name="runScenario" time="0.140"/>
  <testcase classname="test_runner_team08.TestRunner" name="runScenario" time="0.121"/>
  <testcase classname="test_runner_team08.TestRunner" name="runScenario" time="0.145"/>
  <testcase classname="test_runner_team08.TestRunner" name="runScenario" time="0.123"/>
  <testcase classname="test_runner_team08.TestRunner" name="runScenario" time="0.242"/>
  <testcase classname="test_runner_team08.TestRunner" name="runScenario" time="0.167"/>
  <testcase classname="test_runner_team08.TestRunner" name="runScenario" time="0.174"/>
  <testcase classname="test_runner_team08.TestRunner" name="runScenario" time="0.132">
    <error message="parameterValue cannot be null" type="java.lang.IllegalArgumentException">
      <![CDATA[java.lang.IllegalArgumentException: parameterValue cannot be null
at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62)
at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502)
at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:486)
at org.codehaus.groovy.reflection.CachedConstructor.invoke(CachedConstructor.java:73)
at org.codehaus.groovy.reflection.CachedConstructor.doConstructorInvoke(CachedConstructor.java:60)
at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrap.callConstructor(ConstructorSite.java:86)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:277)
at io.restassured.internal.common.assertion.AssertParameter.notNull(AssertParameter.groovy:26)
at io.restassured.internal.common.assertion.AssertParameter$notNull.callStatic(Unknown Source)
at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallStatic(CallSiteArray.java:53)
at io.restassured.internal.common.assertion.AssertParameter$notNull.callStatic(Unknown Source)
at io.restassured.internal.RequestSpecificationImpl.pathParam(RequestSpecificationImpl.groovy:515)
at step_definition_team08.BatchStepDefinition.admin_sends_https_request_with_endpoint_for_program_id_batch_1(BatchStepDefinition.java:522)
at ✽.Admin sends HTTPS Request with endpoint for ProgramID batch(file:///Users/anushakarthick/NumpyNinja/Team_08_APIArchitects_RestAssured/src/test/resources/features/003_BatchModule.feature:181)
]]>
    </error>
  </testcase> <!-- runScenario -->
  <testcase classname="test_runner_team08.TestRunner" name="runScenario" time="0.169"/>
  <testcase classname="test_runner_team08.TestRunner" name="runScenario" time="0.122"/>
  <testcase classname="test_runner_team08.TestRunner" name="runScenario" time="0.129"/>
  <testcase classname="test_runner_team08.TestRunner" name="runScenario" time="0.131"/>
  <testcase classname="test_runner_team08.TestRunner" name="runScenario" time="0.144"/>
  <testcase classname="test_runner_team08.TestRunner" name="runScenario" time="0.123"/>
  <testcase classname="test_runner_team08.TestRunner" name="runScenario" time="0.128"/>
  <testcase classname="test_runner_team08.TestRunner" name="runScenario" time="0.134"/>
  <testcase classname="test_runner_team08.TestRunner" name="runScenario" time="0.150"/>
  <testcase classname="test_runner_team08.TestRunner" name="runScenario" time="0.141"/>
  <testcase classname="test_runner_team08.TestRunner" name="runScenario" time="0.138"/>
  <testcase classname="test_runner_team08.TestRunner" name="runScenario" time="0.614"/>
  <testcase classname="test_runner_team08.TestRunner" name="runScenario" time="0.134"/>
  <testcase classname="test_runner_team08.TestRunner" name="runScenario" time="0.138"/>
  <testcase classname="test_runner_team08.TestRunner" name="runScenario" time="0.150">
    <error message="Cannot invoke &quot;io.restassured.response.Response.statusCode()&quot; because &quot;response&quot; is null" type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException: Cannot invoke "io.restassured.response.Response.statusCode()" because "response" is null
at utilities_team08.CommonValidation.statusValidations(CommonValidation.java:68)
at step_definition_team08.BatchStepDefinition.admin_receives_ok_status_with_message_batch_2(BatchStepDefinition.java:672)
at ✽.Admin receives 200 Ok status with the message batch(file:///Users/anushakarthick/NumpyNinja/Team_08_APIArchitects_RestAssured/src/test/resources/features/003_BatchModule.feature:233)
]]>
    </error>
  </testcase> <!-- runScenario -->
  <testcase classname="test_runner_team08.TestRunner" name="runScenario" time="0.116"/>
  <testcase classname="test_runner_team08.TestRunner" name="runScenario" time="0.135"/>
  <testcase classname="test_runner_team08.TestRunner" name="runScenario" time="0.149"/>
  <testcase classname="test_runner_team08.TestRunner" name="runScenario" time="0.160"/>
  <testcase classname="test_runner_team08.TestRunner" name="runScenario" time="0.142"/>
  <testcase classname="test_runner_team08.TestRunner" name="runScenario" time="0.154"/>
  <testcase classname="test_runner_team08.TestRunner" name="runScenario" time="0.133"/>
  <testcase classname="test_runner_team08.TestRunner" name="runScenario" time="0.145"/>
  <testcase classname="test_runner_team08.TestRunner" name="runScenario" time="0.243"/>
  <testcase classname="test_runner_team08.TestRunner" name="runScenario" time="0.228"/>
  <testcase classname="test_runner_team08.TestRunner" name="runScenario" time="0.160"/>
  <testcase classname="test_runner_team08.TestRunner" name="runScenario" time="0.138">
    <failure message="1 expectation failed.
Expected status code &lt;404&gt; but was &lt;200&gt;.
" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: 1 expectation failed.
Expected status code <404> but was <200>.

at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62)
at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502)
at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:486)
at org.codehaus.groovy.reflection.CachedConstructor.invoke(CachedConstructor.java:73)
at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrapNoCoerce.callConstructor(ConstructorSite.java:108)
at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallConstructor(CallSiteArray.java:57)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:263)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:277)
at io.restassured.internal.ResponseSpecificationImpl$HamcrestAssertionClosure.validate(ResponseSpecificationImpl.groovy:512)
at io.restassured.internal.ResponseSpecificationImpl$HamcrestAssertionClosure$validate$1.call(Unknown Source)
at io.restassured.internal.ResponseSpecificationImpl.validateResponseIfRequired(ResponseSpecificationImpl.groovy:696)
at io.restassured.internal.ResponseSpecificationImpl.this$2$validateResponseIfRequired(ResponseSpecificationImpl.groovy)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.codehaus.groovy.runtime.callsite.PlainObjectMetaMethodSite.doInvoke(PlainObjectMetaMethodSite.java:43)
at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:198)
at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.callCurrent(PogoMetaMethodSite.java:62)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:185)
at io.restassured.internal.ResponseSpecificationImpl.statusCode(ResponseSpecificationImpl.groovy:135)
at io.restassured.specification.ResponseSpecification$statusCode$0.callCurrent(Unknown Source)
at io.restassured.internal.ResponseSpecificationImpl.statusCode(ResponseSpecificationImpl.groovy:143)
at io.restassured.internal.ValidatableResponseOptionsImpl.statusCode(ValidatableResponseOptionsImpl.java:89)
at step_definition_team08.BatchStepDefinition.admin_receives_status_with_error_message_not_found_batch_1(BatchStepDefinition.java:466)
at ✽.Admin receives 404 status with error message Not Found batch.(file:///Users/anushakarthick/NumpyNinja/Team_08_APIArchitects_RestAssured/src/test/resources/features/003_BatchModule.feature:86)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase classname="test_runner_team08.TestRunner" name="runScenario" time="0.130"/>
  <testcase classname="test_runner_team08.TestRunner" name="runScenario" time="0.425">
    <failure message="Status validation expected:&lt;400&gt; but was:&lt;201&gt;" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Status validation expected:<400> but was:<201>
at org.junit.Assert.fail(Assert.java:93)
at org.junit.Assert.failNotEquals(Assert.java:647)
at org.junit.Assert.assertEquals(Assert.java:128)
at org.junit.Assert.assertEquals(Assert.java:472)
at utilities_team08.CommonValidation.statusValidations(CommonValidation.java:71)
at step_definition_team08.UserModuleStepDefinition.admin_receives_bad_request_status_with_message_and_boolean_success_details(UserModuleStepDefinition.java:286)
at ✽.Admin receives 400 Bad Request Status with message and boolean success details(file:///Users/anushakarthick/NumpyNinja/Team_08_APIArchitects_RestAssured/src/test/resources/features/004_User_Module_and_BatchProgramMap.feature:67)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase classname="test_runner_team08.TestRunner" name="runScenario" time="0.123"/>
  <testcase classname="test_runner_team08.TestRunner" name="runScenario" time="0.157"/>
  <testcase classname="test_runner_team08.TestRunner" name="runScenario" time="0.534"/>
  <testcase classname="test_runner_team08.TestRunner" name="runScenario" time="0.122"/>
  <testcase classname="test_runner_team08.TestRunner" name="runScenario" time="0.154"/>
  <testcase classname="test_runner_team08.TestRunner" name="runScenario" time="0.145"/>
  <testcase classname="test_runner_team08.TestRunner" name="runScenario" time="1.306"/>
  <testcase classname="test_runner_team08.TestRunner" name="runScenario" time="0.353"/>
  <testcase classname="test_runner_team08.TestRunner" name="runScenario" time="0.140"/>
  <testcase classname="test_runner_team08.TestRunner" name="runScenario" time="0.144"/>
  <testcase classname="test_runner_team08.TestRunner" name="runScenario" time="0.142"/>
  <testcase classname="test_runner_team08.TestRunner" name="runScenario" time="0.140"/>
  <testcase classname="test_runner_team08.TestRunner" name="runScenario" time="0.134"/>
  <testcase classname="test_runner_team08.TestRunner" name="runScenario" time="0.134">
    <failure message="1 expectation failed.
Expected status code &lt;404&gt; but was &lt;200&gt;.
" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: 1 expectation failed.
Expected status code <404> but was <200>.

at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62)
at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502)
at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:486)
at org.codehaus.groovy.reflection.CachedConstructor.invoke(CachedConstructor.java:73)
at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrapNoCoerce.callConstructor(ConstructorSite.java:108)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:277)
at io.restassured.internal.ResponseSpecificationImpl$HamcrestAssertionClosure.validate(ResponseSpecificationImpl.groovy:512)
at io.restassured.internal.ResponseSpecificationImpl$HamcrestAssertionClosure$validate$1.call(Unknown Source)
at io.restassured.internal.ResponseSpecificationImpl.validateResponseIfRequired(ResponseSpecificationImpl.groovy:696)
at io.restassured.internal.ResponseSpecificationImpl.this$2$validateResponseIfRequired(ResponseSpecificationImpl.groovy)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.codehaus.groovy.runtime.callsite.PlainObjectMetaMethodSite.doInvoke(PlainObjectMetaMethodSite.java:43)
at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:198)
at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.callCurrent(PogoMetaMethodSite.java:62)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:185)
at io.restassured.internal.ResponseSpecificationImpl.statusCode(ResponseSpecificationImpl.groovy:135)
at io.restassured.specification.ResponseSpecification$statusCode$0.callCurrent(Unknown Source)
at io.restassured.internal.ResponseSpecificationImpl.statusCode(ResponseSpecificationImpl.groovy:143)
at io.restassured.internal.ValidatableResponseOptionsImpl.statusCode(ValidatableResponseOptionsImpl.java:89)
at step_definition_team08.BatchStepDefinition.admin_receives_not_found_status_with_message_and_boolean_success_details_batch_1(BatchStepDefinition.java:590)
at ✽.Admin receives 404 Not Found Status with the message and boolean success details batch(file:///Users/anushakarthick/NumpyNinja/Team_08_APIArchitects_RestAssured/src/test/resources/features/003_BatchModule.feature:158)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase classname="test_runner_team08.TestRunner" name="runScenario" time="0.126"/>
  <testcase classname="test_runner_team08.TestRunner" name="runScenario" time="0.247"/>
  <testcase classname="test_runner_team08.TestRunner" name="runScenario" time="0.122"/>
  <testcase classname="test_runner_team08.TestRunner" name="runScenario" time="0.260"/>
  <testcase classname="test_runner_team08.TestRunner" name="runScenario" time="0.156"/>
  <testcase classname="test_runner_team08.TestRunner" name="runScenario" time="1.655"/>
  <testcase classname="test_runner_team08.TestRunner" name="runScenario" time="0.123"/>
  <testcase classname="test_runner_team08.TestRunner" name="runScenario" time="0.220"/>
  <testcase classname="test_runner_team08.TestRunner" name="runScenario" time="0.146"/>
  <testcase classname="test_runner_team08.TestRunner" name="runScenario" time="0.146"/>
  <testcase classname="test_runner_team08.TestRunner" name="runScenario" time="0.144"/>
  <testcase classname="test_runner_team08.TestRunner" name="runScenario" time="0.138"/>
  <testcase classname="test_runner_team08.TestRunner" name="runScenario" time="0.200"/>
  <testcase classname="test_runner_team08.TestRunner" name="runScenario" time="0.137"/>
  <testcase classname="test_runner_team08.TestRunner" name="runScenario" time="0.121"/>
  <testcase classname="test_runner_team08.TestRunner" name="runScenario" time="0.678">
    <failure message="Status validation expected:&lt;400&gt; but was:&lt;201&gt;" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Status validation expected:<400> but was:<201>
at org.junit.Assert.fail(Assert.java:93)
at org.junit.Assert.failNotEquals(Assert.java:647)
at org.junit.Assert.assertEquals(Assert.java:128)
at org.junit.Assert.assertEquals(Assert.java:472)
at utilities_team08.CommonValidation.statusValidations(CommonValidation.java:71)
at step_definition_team08.UserModuleStepDefinition.admin_receives_bad_request_status_with_message_and_boolean_success_details(UserModuleStepDefinition.java:286)
at ✽.Admin receives 400 Bad Request Status with message and boolean success details(file:///Users/anushakarthick/NumpyNinja/Team_08_APIArchitects_RestAssured/src/test/resources/features/004_User_Module_and_BatchProgramMap.feature:67)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase classname="test_runner_team08.TestRunner" name="runScenario" time="0.188"/>
  <testcase classname="test_runner_team08.TestRunner" name="runScenario" time="0.168"/>
  <testcase classname="test_runner_team08.TestRunner" name="runScenario" time="0.129"/>
  <testcase classname="test_runner_team08.TestRunner" name="runScenario" time="0.137"/>
  <testcase classname="test_runner_team08.TestRunner" name="runScenario" time="0.130"/>
  <testcase classname="test_runner_team08.TestRunner" name="runScenario" time="0.145"/>
  <testcase classname="test_runner_team08.TestRunner" name="runScenario" time="0.161"/>
  <testcase classname="test_runner_team08.TestRunner" name="runScenario" time="0.145"/>
  <testcase classname="test_runner_team08.TestRunner" name="runScenario" time="0.007">
    <error message="parameterValue cannot be null" type="java.lang.IllegalArgumentException">
      <![CDATA[java.lang.IllegalArgumentException: parameterValue cannot be null
at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62)
at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502)
at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:486)
at org.codehaus.groovy.reflection.CachedConstructor.invoke(CachedConstructor.java:73)
at org.codehaus.groovy.reflection.CachedConstructor.doConstructorInvoke(CachedConstructor.java:60)
at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrap.callConstructor(ConstructorSite.java:86)
at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallConstructor(CallSiteArray.java:57)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:263)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:277)
at io.restassured.internal.common.assertion.AssertParameter.notNull(AssertParameter.groovy:26)
at io.restassured.internal.common.assertion.AssertParameter$notNull.callStatic(Unknown Source)
at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallStatic(CallSiteArray.java:53)
at io.restassured.internal.common.assertion.AssertParameter$notNull.callStatic(Unknown Source)
at io.restassured.internal.RequestSpecificationImpl.pathParam(RequestSpecificationImpl.groovy:515)
at step_definition_team08.BatchStepDefinition.admin_sends_https_request_with_endpoint_for_program_id_batch_1(BatchStepDefinition.java:522)
at ✽.Admin sends HTTPS Request with endpoint for ProgramID batch(file:///Users/anushakarthick/NumpyNinja/Team_08_APIArchitects_RestAssured/src/test/resources/features/003_BatchModule.feature:139)
]]>
    </error>
  </testcase> <!-- runScenario -->
  <testcase classname="test_runner_team08.TestRunner" name="runScenario" time="0.132"/>
  <testcase classname="test_runner_team08.TestRunner" name="runScenario" time="0.139"/>
  <testcase classname="test_runner_team08.TestRunner" name="runScenario" time="0.129"/>
  <testcase classname="test_runner_team08.TestRunner" name="runScenario" time="0.185"/>
  <testcase classname="test_runner_team08.TestRunner" name="runScenario" time="0.136"/>
  <testcase classname="test_runner_team08.TestRunner" name="runScenario" time="0.163"/>
  <testcase classname="test_runner_team08.TestRunner" name="runScenario" time="0.129">
    <failure message="1 expectation failed.
Expected status code &lt;200&gt; but was &lt;404&gt;.
" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: 1 expectation failed.
Expected status code <200> but was <404>.

at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62)
at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502)
at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:486)
at org.codehaus.groovy.reflection.CachedConstructor.invoke(CachedConstructor.java:73)
at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrapNoCoerce.callConstructor(ConstructorSite.java:108)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:277)
at io.restassured.internal.ResponseSpecificationImpl$HamcrestAssertionClosure.validate(ResponseSpecificationImpl.groovy:512)
at io.restassured.internal.ResponseSpecificationImpl$HamcrestAssertionClosure$validate$1.call(Unknown Source)
at io.restassured.internal.ResponseSpecificationImpl.validateResponseIfRequired(ResponseSpecificationImpl.groovy:696)
at io.restassured.internal.ResponseSpecificationImpl.this$2$validateResponseIfRequired(ResponseSpecificationImpl.groovy)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.codehaus.groovy.runtime.callsite.PlainObjectMetaMethodSite.doInvoke(PlainObjectMetaMethodSite.java:43)
at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:198)
at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.callCurrent(PogoMetaMethodSite.java:62)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:185)
at io.restassured.internal.ResponseSpecificationImpl.statusCode(ResponseSpecificationImpl.groovy:135)
at io.restassured.specification.ResponseSpecification$statusCode$0.callCurrent(Unknown Source)
at io.restassured.internal.ResponseSpecificationImpl.statusCode(ResponseSpecificationImpl.groovy:143)
at io.restassured.internal.ValidatableResponseOptionsImpl.statusCode(ValidatableResponseOptionsImpl.java:89)
at step_definition_team08.BatchStepDefinition.admin_receives_ok_status_with_batch_status_field_in_the_response_body_batch_1(BatchStepDefinition.java:549)
at ✽.Admin receives 200 OK Status with  batchStatus field "Inactive" in the response body batch.(file:///Users/anushakarthick/NumpyNinja/Team_08_APIArchitects_RestAssured/src/test/resources/features/003_BatchModule.feature:98)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase classname="test_runner_team08.TestRunner" name="runScenario" time="0.159"/>
  <testcase classname="test_runner_team08.TestRunner" name="runScenario" time="0.120"/>
</testsuite> <!-- test_runner_team08.TestRunner -->
